// This runner is auto-generated by Brittle

runTests()

async function runTests () {
  const test = (await import('brittle')).default

  test.pause()

  await import('./async-iterator.js')
  await import('./backpressure.js')
  await import('./byte-length.js')
  await import('./compat.js')
  await import('./destroy.js')
  await import('./duplex.js')
  await import('./get-stream-error.js')
  await import('./passthrough.js')
  await import('./pipe.js')
  await import('./pipeline.js')
  await import('./readable.js')
  await import('./transform.js')
  await import('./writable.js')

  test.resume()
}
